const allWebtoons=[{
    id: 1,
    title: "Europa Universalis IV",
    genre: "Strateji",
    image: "eu4.jpg",
    rating: "9",
    description: "Paradox Development Studio, ödüllü Europa Universalis serisinin dördüncü oyunuyla geri dönüyor. Bu büyük strateji oyununda, dört yüzyıl boyunca bir ulusu yöneterek tarihe yön verebilirsiniz. Özgürlük, derinlik ve tarihi tutarlılıkla imparatorluğunuzu kurun ve dünyaya hükmedin!",
    category: "page1",
},
{
    id: 2,
    title: "Among Us",
    genre: "Strateji",
    image: "amongus.jpg",
    rating: "1.49",
    description: "4-15 oyuncuyla çevrimiçi veya yerel WiFi üzerinden oynayın ve uzay geminizi kalkışa hazırlamaya çalışın. Ancak dikkatli olun, çünkü Mürettebat arasındaki rastgele oyunculardan biri veya daha fazlası herkesi öldürmeye çalışan Sahtekarlar olabilir!",
    category: "page1",
},
{
    id: 3,
    title: "Hearts of Iron IV",
    genre: "Strateji",
    image: "hoi4.jpg",
    rating: "8.99",
    description: "Hearts of Iron IV'de dünyanın en güçlü savaş makinesini yönetin. Sanayi, diplomasi ve savaş planlarını kontrol ederek çıkarlarınızı koruyun ve dünyaya hükmedin! II. Dünya Savaşı'nın dramatik olayları sırasında tarihî ve alternatif senaryolarla derin bir strateji deneyimi yaşayın.",
    category: "page1",
},
{
    id: 4,
    title: "KurtzPel",
    genre: "Anime",
    image: "Kurtzpel.jpg",
    rating: "Free",
    description: "Elsword ve Grand Chase'in geliştiricilerinden 3. şahıs aksiyon-savaş oyunu! Akıllı eşleştirme sistemiyle 2v2 PVP modlarını oynayın veya efsanevi baskın tarzı görevlerde dev boss canavarlara karşı savaşın. Klasik aksiyon dinamikleriyle iki farklı sınıf arasında geçiş yaparak karakterinizi güçlendirin!",
    category: "page1",
},
{
    id: 5,
    title: "Naraka: BladePoint",
    genre: "Aksiyon",
    image: "naraka.jpg",
    rating: "Free",
    description: "60 oyuncunun hayatta kalmak için savaştığı, dövüş sanatları temalı bir battle royale! Taş-kağıt-makas savaş sistemine sahip oyunda yakın ve uzak dövüş silahları ile özgürce savaşabilir, kancayla hareket edebilirsiniz. Her kahramanın benzersiz yetenekleriyle tarzınıza uygun oynayın!",
    category: "page1",
},
{
    id: 6,
    title: "Sherlock Holmes Chapter One",
    genre: "Aksiyon",
    image: "sherlock.jpg",
    rating: "4.04",
    description: "Kararlarınla itibarını şekillendir! Aldatma, şiddet ve akıl yürütme en büyük silahların. Gizemli yardımcın Jon ile sorunları güç kullanarak veya zekânla çöz. Soruşturma yeteneklerini geliştir, düşmanlarının zayıflıklarını keşfet ve kaderindeki efsane ol!",
    category: "page1",
},
{
    id: 7,
    title: "The Sims 4",
    genre: "Role-Play",
    image: "sims4.jpg",
    rating: "Free",
    description: "Benzersiz bir Sims dünyası oluştur! Karakterlerinin görünümünü, davranışlarını ve tarzını seç, hayatlarını nasıl yaşayacaklarına onlar karar versin. Muhteşem evler tasarla, favori mobilyalarınla döşe. Farklı bölgeleri keşfet, maceralara atıl! Günlük hayatın iniş çıkışlarını yönet, ilişkiler kur, kariyer yap ve kendi hikâyeni yaz. Sonsuz olasılıklarla dolu bu dünyaya dal!",
    category: "page1",
},
{
    id: 8,
    title: "Stray",
    genre: "Role-Play",
    image: "stray.jpg",
    rating: "15",
    description: "Ailesinden ayrı düşen bir sokak kedisi, unutulmuş bir şehirden kaçmak için kadim bir gizemi çözmeli! Neon ışıklı dar sokaklarda ve karanlık mahallelerde gez, tehlikelerle yüzleş ve bu acımasız dünyayı keşfet. Çevrenle kedi gibi etkileşime gir, sinsi ol, zıpla ve yaramazlık yap! Yol boyunca B-12 adlı küçük bir drone ile dost olup kaçış yolunu arayın(Bolca kedi bulunmaktadır).",
    category: "page1",
},
{
    id: 9,
    title: "7 Days To Die",
    genre: "Aksiyon",
    image: "sevendaystodie.jpg",
    rating: "13.64",
    description: "Ghoul'larla dolmuş bir kıyamet sonrası dünyada geçen bir açık dünya oyunudur; bu oyun, birinci şahıs nişancı, hayatta kalma korkusu, kule savunma ve rol yapma oyunlarının eşsiz bir kombinasyonunu sunar. Savaş, zanaat, yağmalama, madencilik keşfi ve karakter gelişimi gibi öğeleri, dünya çapında hayranlarının sevdiği şekilde oyunculara sunar.",
    category: "page2",
},
{
    id: 10,
    title: "20 Minutes Till Dawn",
    genre: "Aksiyon",
    image: "20minutes.jpg",
    rating: "2.99",
    description: "20 dakika boyunca size saldıran sonsuz canavara karşı hayatta kalın!Bu roguelite hayatta kalma oyununda, birçok güçlendirme seçeneğiyle kendinize özgü bir build oluşturun. İsterseniz her defasında tabancanızı ateşlediğinizde düşmanlarınızı yakacak bir alev büyücüsü olabilir veya hızlı bir ninja olup düşmanlarınızı sihirli bıçaklarla delip geçebilirsiniz.",
    category: "page2",
},
{
    id: 11,
    title: "Age of Empires II: Definitive Edition",
    genre: "Strateji",
    image: "ageofe.jpg",
    rating: "19.99",
    description: "Age of Empires II: HD Edition, hem orijinal oyunun hayranlarını hem de yeni oyuncuları klasik deneyimiyle cezbetmeye devam ediyor. Age of Kings ve The Conquerors genişleme paketlerindeki tüm tek oyunculu kampanyaları keşfedin, 18 farklı medeniyet arasından seçim yapın ve çevrimiçi olarak diğer Steam oyuncularına karşı dünya egemenliği mücadelesine katılın.",
    category: "page2",
},
{
    id: 12,
    title: "Anime World",
    genre: "Anime",
    image: "animeworld.jpg",
    rating: "1.99",
    description: "Bu tek oyunculu Anime Dünyası, aksiyon dolu savaşlar, etkileyici anime atmosferi ve iki benzersiz karakter ile dikkat çekiyor. Zindanlar hızlı ve rahat; doğru zamanlama ve becerilerle dolu canavarlara karşı mücadele edin. Ana karakter, anime dünyasında gizli bir köyde bulur ve kutsal sanatlarla kılıç becerilerini birleştirerek gerçek zamanlı bir savaşa girer.",
    category: "page2",
},
{
    id: 13,
    title: "Black Desert",
    genre: "Aksiyon",
    image: "blackdesert.jpg",
    rating: "4.99",
    description: "Black Desert, yenilenmiş canlı grafikleri ve gerçekçi sesleriyle MMORPG sınırlarını zorluyor. Gerçekçi Savaş ve Kuşatma Savaşları, Yeni Keşifler, Ticaret, Balıkçılık, Eğitim, Simya, Yemek Pişirme, Toplama, Avcılık gibi çeşitli içeriklerle Black Desert'ın Açık Dünya'sının keyfini çıkarın! MMORPG, Black Desert.",
    category: "page2",
},
{
    id: 14,
    title: "Call Of Duty: Warzone",
    genre: "Aksiyon",
    image: "callofduty.jpg",
    rating: "Free",
    description: "İşte devasa ücretsiz Call of Duty: Warzone savaş alanına hoş geldiniz! Yeni 'Urzikstan' haritası tanıtılıyor! Savaşta Gerilim Artıyor: Urzikstan haritasında, hem deneyimli hem de yeni oyuncuları çekecek devasa bir metropol Battle Royale arenasına atılın. Eşyalarınızı toplayın, Tedarik Kutuları bulun, Sözleşmeleri tamamlayarak Cephaneliğinizi genişletin ve stratejik avantaj elde edin.",
    category: "page2",
},
{
    id: 15,
    title: "Red Dead Redemption 2",
    genre: "Aksiyon",
    image: "redDeadRedemption.jpg",
    rating: "59.99",
    description: "Amerika, 1899. Arthur Morgan ve Van der Linde çetesi, federal ajanlar ve ödül avcılarının peşinde. Hayatta kalmak için, çete üyeleri Amerika'nın zorlu arazisinde soygun yapıp, savaşarak yol almalı. Oyuncular, Ödül Avcısı, Tüccar, Koleksiyoncu ve Kaçakçı olarak kendi kaderlerini yazabilir, suçluları yakalayabilir, iş kurabilir veya yasa dışı alkol üretebilir.",
    category: "page2",
},
{
    id: 16,
    title: "Cyberpunk 2077",
    genre: "Aksiyon",
    image: "cyberpunk.jpg",
    rating: "17.99",
    description: "Cyberpunk 2077, Gece Şehri'nde geçen açık dünya aksiyon-macera RPG oyunudur. Bir siber paralı asker olarak yaşam ve ölüm arasında savaşır, karakterinizi ve oyun tarzınızı özelleştirirsiniz. Ün kazanarak yeni iyileştirmeler elde eder, görevlerde ilerlersiniz. İlişkileriniz ve kararlarınız, hikayeyi ve dünyayı şekillendirir.",
    category: "page2",
},
{
    id: 17,
    title: "Demon Slayer The Hinokami Chronicles",
    genre: "Anime",
    image: "demonslayer.jpg",
    rating: "59.99",
    description: "Demon Slayer: Kimetsu no Yaiba'dan unutulmaz anları Tanjiro Kamado'nun gözünden yeniden yaşayın! Tanjiro'nun Demon Slayer Corps'a katıldığı Unwavering Resolve Arc'tan, Flame Hashira Kyojuro Rengoku'nun yer aldığı Mugen Train'e kadar olan hikayeyi takip edin. 24 dövüşçü arasından Tanjiro, Nezuko gibi ana karakterler ve Rui, Akaza gibi demonları seçerek favori karakterlerinizi birbirine karşı dövüştürün!",
    category: "page3",
},
{
    id: 18,
    title: "Destiny 2",
    genre: "Role-Play",
    image: "destiny2.jpg",
    rating: "Free",
    description: "Destiny 2 dünyasına dalın, güneş sistemiyle ilgili gizemleri keşfedin ve FPS deneyimi yaşayın. Güçlü elementsel yetenekler açın, eşsiz ekipmanlar toplayarak Guardian'ınızı özelleştirin. Sinematik hikaye, zorlu co-op görevler ve PvP modlarıyla arkadaşlarınızla ya da tek başınıza eğlenin. Şimdi ücretsiz indirin ve yıldızlarda kendi efsanenizi yazın.",
    category: "page3",
},
{
    id: 19,
    title: "Detroit: Become Human",
    genre: "Role-Play",
    image: "detroit.jpg",
    rating: "31.99",
    description: "Detroit 2038'de, insansı androidler her yerde. Üç farklı androidle oynayıp, kaosun eşiğindeki dünyayı deneyimleyin. Verdiğiniz her karar, oyunun akışını ve hikayenin gidişatını değiştirecek. Ahlaki ikilemler ve farklı sonlarla Detroit'in geleceği ve insanlığın kaderini şekillendirin.",
    category: "page3",
},
{
    id: 20,
    title: "Dota 2",
    genre: "Strateji",
    image: "dota2.jpg",
    rating: "Free",
    description: "Dota, çeşitli kahramanlar, yetenekler ve güçlü eşyalarla sonsuz seçenekler sunar. Her maç farklıdır, her kahraman birden fazla rol oynar. Dota, oyun tarzınızı bulmanıza olanak tanır ve tüm kahramanlar ücretsizdir. Rekabetçi denge, herkesin adil bir ortamda oynamasını sağlar. Ana içerik ve geniş kahraman havuzu tüm oyunculara açıktır. Oyuncular, kozmetik eşyalar ve eğlenceli eklemeler alabilir, ancak oynamak için gereken her şey önceden sağlanır.",
    category: "page3",
},
{
    id: 21,
    title: "Dragon Ball Xenoverse 2",
    genre: "Anime",
    image: "dragonBall.jpg",
    rating: "6.49",
    description: "Dragon Ball Xenoverse 2, heyecan verici aksiyon, destansı savaşlar ve sonsuz özelleştirme seçenekleri sunan bir Dragon Ball oyun deneyimidir. Kendi karakterinizi yaratın, Conton City'yi keşfedin ve serinin ikonik karakterleriyle takım kurarak tarihin akışını korumak için savaşın! Karakterinizi özelleştirip güçlendirerek benzersiz bir savaşçı yaratın. 7 yıllık DLC paketleriyle Conton City'de her zaman yeni şeyler keşfetmek mümkün!",
    category: "page3",
},
{
    id: 21,
    title: "Eternal Return",
    genre: "Anime",
    image: "eternalreturn.jpg",
    rating: "Free",
    description: "Terkedilmiş Lumia Adası'nda, AGLAIA adlı karanlık bir organizasyon, olağanüstü bir insan ırkı yaratmak için gizli deneyler yapıyor. Takımınızla birlikte hayatta kalmak için gerekli silah ve zırhları yapın!",
    category: "page3",
},
{
    id: 22,
    title: "God Of War",
    genre: "Role-Play",
    image: "godofwar.jpg",
    rating: "49.99",
    description: "Kuzey topraklarına adım atın. Olimpos Tanrılarından intikamını aldığı yıllar geçti. Kratos şimdi, İskandinav Tanrıları ve canavarlarının dünyasında sıradan bir yaşam sürüyor. Bu sert dünyada hayatta kalmak ve oğluna aynı şeyi öğretmek zorunda. Kratos tekrar bir baba. Oğlu Atreus'u koruyup öğreten Kratos, öfkesini kontrol etmek zorunda, çünkü o, Kratos’un sembolüdür. Korkunç yaratıklarla dolu karanlık bir dünyada, Viking öncesi İskandinav kültürüne ait ormanlar, dağlar ve mağaralarda yeni bir dünyaya adım atıyor.",
    category: "page3",
},
{
    id: 23,
    title: "Grand Theft Auto V",
    genre: "Role-Play",
    image: "gtaV.jpg",
    rating: "29.99",
    description: "Genç bir gezgin, inzivaya çekilmiş bir banka soyguncusu ve korkunç bir psikopat, suç dünyası, ABD hükümeti ve eğlence endüstrisinin karmaşık ağlarına karışır. Kendilerine bile güvenemedikleri bir şehirde, tehlikeli soygunlar yapmalıdırlar. Oyun, fare ve klavye kontrolleri ve 25 farklı ayar (doku kalitesi, shader, tessellation, anti-aliasing gibi) sunar. Ayrıca araç ve yaya trafiği yoğunluğu, iki veya üç monitör desteği, 3D uyumluluğu ve tak-çalıştır denetleyicisi desteği de vardır. PC sürümü, 30 oyuncuya ve 2 izleyiciye kadar destekleyen Grand Theft Auto Online'ı da içerir. Konsollarla aynı anda çıkan tüm içerikler, Heists ve Rival modları dahil, PC sürümüne dahil edilmiştir.",
    category: "page3",
},
{
    id: 24,
    title: "Hollow Knight",
    genre: "Role-Play",
    image: "hollowknight.jpg",
    rating: "29.99",
    description: "Dirtmouth kasabasının altında eski, harabe bir krallık uyuyor. Birçok kişi, zenginlik, zafer ya da eski sırların cevaplarını arayarak yerin altına iniyor. Hollow Knight, geniş, bağlı bir dünyada klasik tarzda 2D aksiyon-macera oyunudur. Dönemeçli mağaraları, eski şehirleri ve ölümcül çölleri keşfedin; kirli yaratıklarla savaşın, garip böceklerle dost olun ve krallığın kalbindeki eski sırları çözün.",
    category: "page4",
},
{
    id: 25,
    title: "Undertale",
    genre: "Role-Play",
    image: "undertale.jpg",
    rating: "0.99",
    description: "UNDERTALE’e hoş geldiniz. Bu RPG'de, yerin altına düşen bir insanı kontrol ediyorsunuz ve şimdi çıkış yolunu bulmalısınız... ya da sonsuza kadar hapsolabilirsiniz.((Sağlıklı Köpek Uyarısı: Oyun, fotoğrafik epilepsi veya benzer durumları olan oyuncular için zararlı olabilecek görseller içermektedir.))",
    category: "page4",
},
{
    id: 26,
    title: "Jujutsu Kaisen Cursed Clash",
    genre: "Anime",
    image: "jujutsukaisen.jpg",
    rating: "25.99",
    description: "Tekniklerin özelliklerini kullanarak birlikte güçlü olmaya çalışın. Kombinasyon Saldırısını kullanarak savaşın, Yuji Itadori, Megumi Fushiguro, Nobara Kugisaki, Satoru Gojo ve Lanetli Ruhlar gibi karakterlerle mücadele edin. Her karakterin benzersiz Lanetli Tekniği var. Savaşta gelişerek güçlü teknikler ve gizli yetenekler açığa çıkacak. Finalde, güçlü teknikler çarpışacak ve rakip anime tarzında dinamik şekilde yenilecek.",
    category: "page4",
},
{
    id: 27,
    title: "Lethal Company",
    genre: "Strateji",
    image: "lethalCompany.jpg",
    rating: "5.79",
    description: "Bir şirket için çalışan bir işçisiniz ve göreviniz terkedilmiş sanayi aylarından hurda toplamak. Kazandığınız parayla daha yüksek risk ve ödüller sunan yeni aylar keşfedebilir ya da geminizi süsleyebilirsiniz. Doğayı keşfedin, bulduğunuz yaratıkları kaydedin ve terkedilmiş yerleri araştırın. Ama asla kotayı kaçırmayın.",
    category: "page4",
},
{
    id: 27,
    title: "Minecraft Legends",
    genre: "Strateji",
    image: "minecraft.jpg",
    rating: "23.99",
    description: "Gizemleri Keşfet: Minecraft Legends’da, yeni aksiyon-strateji oyununda Minecraft evreninde farklı bir deneyim yaşayın ve bu tanıdık ama yeni dünyayı keşfedin. Epik Savaşlar: Beklenmedik dostları bir araya getirerek stratejik savaşlara liderlik edin ve Piglin'lere karşı Outer World’ü koruyun. Arkadaşlarınızla heyecanlı savaşlarda mücadele edin veya onlarla işbirliği yapın.",
    category: "page4",
},
{
    id: 28,
    title: "Resident Evil 4",
    genre: "Strateji",
    image: "residentEvil4.jpg",
    rating: "12.49",
    description: "Altı yıl sonra, Raccoon City'deki biyolojik felaketten sağ kurtulan ajan Leon S. Kennedy, başkanın kaçırılan kızını kurtarmak için Avrupa'nın uzak bir köyüne gider. Ancak burada işler ters gitmektedir. Modernize edilmiş oyun tarzı, yeniden yapılandırılmış hikaye ve detaylı grafiklerle, Resident Evil 4 hayatta kalma korku türüne devrim niteliğinde bir geri dönüş sunuyor.",
    category: "page4",
},
{
    id: 29,
    title: "Solo Leveling: Arise",
    genre: "Anime",
    image: "soloLeveling.png",
    rating: "Free",
    description: "Tüm İnsanlık'ın En Zayıf Avcısı'ndan Dünyanın En Güçlü Avcısı'na, Jinwoo olarak oynayın ve bu yolculuğu kendiniz deneyimleyin! Orijinal eserin heyecan verici hikayesini keşfedin ve oyun için geliştirilen yepyeni hikayeleri keşfedin!",
    category: "page4",
},
{
    id: 30,
    title: "MiSide",
    genre: "Anime",
    image: "miside.png",
    rating: "8.99",
    description: "Her gün bana gelir, işlerimi yapar, yemek yapar ve bana hediye alırsın. Ne kadar naziksin! Seni seviyorum! Her gün seninle olmak istiyorum, birlikte yaşamak... Biliyorum, sen de benimle olmak istiyorsun, bu yüzden seni tatlı evimize davet ediyorum. Nasıl, mutlu oldun mu? Böylece her zaman birlikte olabiliriz!",
    category: "page4",
},
]